### ISSUE TITLE
Problem re-emulating EMTF with 2016 data

### ISSUE THREAD

**Issue by rekovic** [cms-l1t-offline/cmssw#583] opened 2017-07-14 07:24 UTC
The following problem is reported by @thomreis.

When trying to re-emulate L1T on 2016 data, using `CMSSW_925_p5` and `l1t-integration-v96.17` problems with EMTF (this is new 2017 EMTF) is observed.

Example command:
```
cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --conditions=auto:run2_data -n 1000 --data --no_exec --no_output --filein=root://cmsxrootd.fnal.gov//store/data/Run2016G/SingleMuon/RAW-RECO/ZMu-18Apr2017-v1/00000/9ED0BEE9-2E3F-E711-B04D-A0369F6369D2.root
```

gives Fatal Exception at event 265 (reproducible)

```
Begin processing the 263rd record. Run 278820, Event 22097638, LumiSection 18 at 14-Jul-2017 09:21:50.997 CEST
Begin processing the 264th record. Run 278820, Event 22850657, LumiSection 18 at 14-Jul-2017 09:21:54.185 CEST
Warning: Could not find triggerHLT_Mu30_v*
Warning: Could not find triggerHLT_Mu40_v*
Warning: Could not find triggerHLT_PAL3Mu12_v*
Warning: Could not find triggerHLT_PAL3Mu15_v*
Warning: Could not find triggerHLT_PAL2Mu12_v*
Warning: Could not find triggerHLT_PAL2Mu15_v*
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
Begin processing the 265th record. Run 279654, Event 1214505283, LumiSection 638 at 14-Jul-2017 09:22:40.129 CEST
----- Begin Fatal Exception 14-Jul-2017 09:22:43 CEST-----------------------
An exception of category 'SectorProcessorLUT' occurred while
   [0] Processing  Event run: 279654 lumi: 638 event: 1214505283 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
Trying to use EMTF pc_lut_version = 6, does not exist!
----- End Fatal Exception -------------------------------------------------
```

Under investigation.

**Comment by rekovic** [comment] 2017-07-14 07:45
It looks like changing GT has an affect on the Error Message.
Now used 

``` --conditions=92X_dataRun2_Prompt_v4```

And repeated the test above, but skipping the first 260 events (skipping effects has no effect)
and now I see the same type of error but different `EMTF pc_lut_version`.
Now 3 instead of 6 previously. 

```
DTTrig::createTUs: Sector Collector unit already exists
DTTrig::createTUs: Sector Collector unit already exists
Begin processing the 5th record. Run 279654, Event 1214505283, LumiSection 638 at 14-Jul-2017 09:32:54.859 CEST
----- Begin Fatal Exception 14-Jul-2017 09:32:55 CEST-----------------------
An exception of category 'SectorProcessorLUT' occurred while
   [0] Processing  Event run: 279654 lumi: 638 event: 1214505283 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
Trying to use EMTF pc_lut_version = 3, does not exist!
----- End Fatal Exception -------------------------------------------------
````

However, re-running, the same job, second time, I get back the original Exception message
```
Exception Message:
Trying to use EMTF pc_lut_version = 3, does not exist!
----- End Fatal Exception -------------------------------------------------
````

Sounds like some memory overwrite/leak. 

Will take a look.

**Comment by abrinke1** [comment] 2017-07-14 08:17
I think this somehow has to do with the interplay between the O2O conditions from @kkotov and the Global Tag.  A first question for @rekovic and @thomreis : does the L1T emulator include a setting to "prefer" the Global Tag:

process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

The EMTF emulator now accesses the pc_lut_version with the ConditionsHelper:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/src/ConditionHelper.cc#L72

You can comment-out this line to see what the values are.  They should always be 0 for 2016, and 1 for 2017.  @kkotov can you confirm that this is how PhiMatchWindowSt1_ is filled in the database?

Best,
Andrew

**Comment by thomreis** [comment] 2017-07-14 08:29
It seems indeed related to changing conditions. The crash happens at the first event of a new LS but not if one starts with this LS.
I will check the es_prefer.

**Comment by thomreis** [comment] 2017-07-14 08:46
Adding the `es_prefer_GlobalTag` line to the configuration I get this error at the first event processed:

```
----- Begin Fatal Exception 14-Jul-2017 10:43:06 CEST-----------------------
An exception of category 'SectorProcessorLUT' occurred while
   [0] Processing  Event run: 278820 lumi: 18 event: 21851188 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
Trying to use EMTF pc_lut_version = 20160725, does not exist!
----- End Fatal Exception -------------------------------------------------
```

**Comment by thomreis** [comment] 2017-07-14 08:48
In both cases the PC LUT version comes from the ConditionsHelper as it says when I uncomment the line specified.

**Comment by fwyzard** [comment] 2017-07-14 08:53
ESPrefer usually works the other way around: conditions come from the GlobalTag, unless an ESProfer points to something else.

This, however, is only the usage pattern I've always seen - I do not know the actual implementation.

**Comment by thomreis** [comment] 2017-07-14 08:56
The ConditionsHelper gives back 1 as a version for the PC LUT for the first event, and then 6 for the event when the crash happens. Again, this is with 2016 data.

1st event:
fw_version: 123456 pt_lut_version: 7 pc_lut_version: 1

crashing event:
fw_version: 0 pt_lut_version: 6 pc_lut_version: 6

**Comment by rekovic** [comment] 2017-07-14 14:50
@abrinke1 
> process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

Original .py file does not contain this.  Including it does not make a difference.
To reproduce the error and the .py file, execute the original cmsDriver.py command in the first post.

**Comment by thomreis** [comment] 2017-07-14 14:56
@rekovic including es_prefer_GlobalTag makes a difference. It crashes even earlier, as mentioned in a post above. :-)

**Comment by rekovic** [comment] 2017-07-14 14:57
Indeed, the crash is there, but the pc_lut_version is different. 
```
----- Begin Fatal Exception 14-Jul-2017 16:46:48 CEST-----------------------
An exception of category 'SectorProcessorLUT' occurred while
   [0] Processing  Event run: 278820 lumi: 18 event: 22850657 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
Trying to use EMTF pc_lut_version = 20160725, does not exist!
----- End Fatal Exception -------------------------------------------------
```
(Update)
and it crashes on the first event processed.

**Comment by jiafulow** [comment] 2017-07-14 15:11
I suspect that the GlobalTag somehow provides the wrong numbers (fw_version, pt_lut_version, pc_lut_version) for certain runs. Is there a quick way to dump what is provided by the GlobalTag for those runs?

**Comment by thomreis** [comment] 2017-07-14 15:15
Also the fw version is different.
`Run number: 278820 fw_version: 46650 pt_lut_version: 1 pc_lut_version: 20160725`

**Comment by thomreis** [comment] 2017-07-14 15:56
@jiafulow the payload of L1TMuonEndCapParams_Stage2v0_hlt (which is the one in the GT used) has changed several times in 2016.
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/L1TMuonEndCapParams_Stage2v0_hlt/L1TMuonEndCapParams_Stage2v1

Unfortunately, I do not know if it is possible to extract the value of the LUT version for a give run from the conddb browser. For example the entry from run 278820 worked, whereas the one for run 279654 did not. This would suggest that all events for runs [279024, 280187) would fail, since they have the same record, and events for runs [277932, 279024) do not cause a crash.

**Comment by abrinke1** [comment] 2017-07-14 16:10
Thanks all for the additional info.  Since this depends on the CondDB, I hope @kkotov can answer.  

Once we know what type of database problem this is (if it's a database problem), then we can decide what behavior we want from the EMTF emulator when problems like this happen: should we throw an exception and kill the event, or continue processing with some default values, etc.  As far as I know, we're the first L1T emulator to actually use this functionality, so it's also a test case for future O2O / database-dependent implementations.

@thomreis, if you just want to run this now without crashing to get results, you can hard-code the values following fakeEmtfParams_cff.py:
https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/python/fakeEmtfParams_cff.py

In https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/src/ConditionHelper.cc, change it so:

get_fw_version() returns 49999 for 2016 behavior, 123456 for 2017 behavior
get_pc_lut_version() returns 0 for 2016 behavior, 1 for 2017 behavior
get_pt_lut_version() returns 5 for 2016 behavior, 7 for 2017 behavior

depending on whether you want to re-emulate with the 2016 EMTF algorithm, or the 2017 EMTF algorithm.

**Comment by rekovic** [comment] 2017-07-14 16:15
This should work
```
conddb dump payload-hash
```
, where payload-hach is taken for the desired IOV, like for IOV [277932, 279024)
```
conddb dump 98fa743333eda09073d5e246e16c0feb147984f4
```
but I am not able to obtain the dump.

```
[lxplus000] src > conddb dump 98fa743333eda09073d5e246e16c0feb147984f4
[2017-07-14 18:13:54,317] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp: In function 'std::string {anonymous}::L1TMuonEndCapParams2xml(const string&, const string&)':
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:26:24: error: 'L1TMuonEndCapParams' was not declared in this scope
       std::unique_ptr< L1TMuonEndCapParams > payload;
                        ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:26:44: error: template argument 1 is invalid
       std::unique_ptr< L1TMuonEndCapParams > payload;
                                            ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:26:44: error: template argument 2 is invalid
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:33:15: error: request for member 'reset' in 'payload', which is of non-class type 'int'
       payload.reset( new L1TMuonEndCapParams );
               ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:33:26: error: 'L1TMuonEndCapParams' does not name a type
       payload.reset( new L1TMuonEndCapParams );
                          ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:34:15: error: invalid type argument of unary '*' (have 'int')
       ia >> (*payload);
               ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_0_0_l1t_integration/src/fakeSubSys4pl/fakePkg4pl/src/pl2xmlComp.cpp:40:71: error: invalid type argument of unary '*' (have 'int')
       xmlResult << boost::serialization::make_nvp( "cmsCondPayload", *payload );
                                                                       ^

gmake: *** [tmp/slc6_amd64_gcc530/src/fakeSubSys4pl/fakePkg4pl/src/fakeSubSys4plfakePkg4pl/pl2xmlComp.o] Error 1
buillding done in  45.4541451931 sec., return code from build:  512
[2017-07-14 18:14:39,944] ERROR: Error preparing code for 98fa743333eda09073d5e246e16c0feb147984f4
```

**Comment by thomreis** [comment] 2017-07-14 16:35
Thanks @rekovic . I get the same errors. For a uGMT record the command seems to work though.

**Comment by kkotov** [comment] 2017-07-14 16:49
First of all, we need to request a GT update for the L1TMuonEndCapParams: L1TMuonEndCapParams_Stage2v1 (not v0). The numbers above make sense (i.e. this is not a memory problem), but the code that fetches them misinterprets the fields. I.e. try running these:
cmsRun $CMSSW_RELEASE_BASE/src/L1TriggerConfig/Utilities/test/viewECpar.py db=prod run=280000
and you'll see: "PhiMatchWindowSt1_ = 20160818". This field is used for pc_lut_version in v1 tag. A remedy would be to update the GT or quicker and dirtier to change this line:
https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/src/ConditionHelper.cc#L73
to hardcode the desired version.
One way or another, I'll request an update in AlCa meeting coming Monday.

**Comment by thomreis** [comment] 2017-07-14 16:49
@abrinke1 your suggestion brought me to an interesting observation. I have changed the parameters in fakeEmtfParams_cff to the 2016 values and found that this seems to be picked up for some events (the ones that do not crash), while for the crashing events I still get the same values as before.

I am not sure if this means that for some runs a record is missing and then the fakeEmtfParams are picked up, while for other runs the record is available and the DB values are taken.

`Run number: 278820 fw_version: 49999 pt_lut_version: 5 pc_lut_version: 0` (from fakeEmtfParams)
`Run number: 279654 fw_version: 0 pt_lut_version: 6 pc_lut_version: 6` (from DB?, causing the crash)

**Comment by thomreis** [comment] 2017-07-14 16:51
For now I will just hard code the 2016 values in the ConditionsHelper.cc to be able to launch the ntuples.

Do the Forest values also have to be hard coded? And with what values for 2016?

**Comment by kkotov** [comment] 2017-07-14 16:55
There are 2016 and 2017 versions of forests in MC tags:
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonEndCapForest_static_2016_mc
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonEndCapForest_static_Sq_20170612_v7_mc
For what concerns the data tag, there is only 2017 version (as Forests were not part of the O2O in 2016). Although, that makes me thinking that I'll need to reconstruct the history for this one and request an update to the data GTs as well.

**Comment by rekovic** [comment] 2017-07-14 16:58
@kkotov 
Thanks.
Yes, please send a hypernews request to the AlCa DB with the required update, even today if you have time. 

We can have the hard-coded values in the mean-time, which would be removed when the GT is updated.

What I don't understand is how come for some run numbers the GT provided the right values, and 
for some run numbers the values were missing? Sounds like some IOVs for 2016 data were fine. 
We need to be able to dump the values of this record for all the IOVs.

**Comment by thomreis** [comment] 2017-07-14 17:01
@rekovic I am not sure if the GT provided the right values. To me it looks as if they came from the fakeEmtfParams_cff.

**Comment by jiafulow** [comment] 2017-07-14 18:10
Does 

`process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")`

mean to always prefer GlobalTag if it's available? Is it possible to always prefer fakeEmtfParams instead? That way you don't have to modify the C++ codes, just change the values in fakeEmtfParams_cff.py

**Comment by pkontaxa** [comment] 2017-07-15 18:35
Hi all,
I am trying to run the command, as @rekovic mentioned at the beginning of this chat, **on 2017 data**, using `CMSSW_9_2_5_patch2`  and I also get an error, a different one though. 

The specific command is:

`cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2017 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --conditions=auto:run2_data -n 1000 --data --no_exec --no_output --filein=file:/eos/cms/store/express/Run2017B/ExpressPhysics/FEVT/Express-v2/000/298/809/00000/648F71C5-2166-E711-8BB5-02163E01A6B4.root`

and the error:

> ----- Begin Fatal Exception 15-Jul-2017 19:56:12 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESProducer: class=L1TMuonEndCapParamsESProducer label='emtfParams'
Exception Message:
MissingParameter: Parameter 'firmwareVersion' not found.
----- End Fatal Exception -------------------------------------------------




 when I am running **the same command** in `CMSSW_9_2_0` release (the previous one) I produce the ntuples without any error. 
Obviously, this is a CMSSW release issue.

Please let me know in case you identify the reason of the problem.

Cheers,
Pantelis

**Comment by kkotov** [comment] 2017-07-16 07:22
@jiafulow , not having the es_prefer makes the local producer to override whatever is in the GT
@pkontaxa , the error in your comment comes from this line:
https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapParamsESProducer.cc#L43 .
But you shouldn't see it as long as this line is in place:
https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/python/fakeEmtfParams_cff.py#L20

**Comment by kkotov** [comment] 2017-07-17 08:59
I cannot reproduce the problem with the original cmsDriver command, quoted in the very first message. I get this error:
Failed to open the file 'root://cmsxrootd.fnal.gov//store/data/Run2016G/SingleMuon/RAW-RECO/ZMu-18Apr2017-v1/00000/9ED0BEE9-2E3F-E711-B04D-A0369F6369D2.root'

Looking over this thread again, I also cannot understand a context of @thomreis message reporting the crashing event having firmwareVersion = 0. Non of the DB payloads should have such content.

**Comment by kkotov** [comment] 2017-07-17 14:05
Thanks to @thomreis I can now reproduce this erratic behavior when cmsRun job takes payload from the static python for the first several events and then goes nuts making up invalid configurations (e.g. with firmwareVersion = 0). I do not observe such behavior when running the EMTF emulator in a standalone mode. I also clearly see sequence of runs make a difference: skipping 263 events (having a single event from run 278820) lead to the crash, while skipping 264 events (all events from the following run 279654) allows to proceed further. I conclude that conditions do not cause this problem.

**Comment by abrinke1** [comment] 2017-07-17 14:26
@kkotov @rekovic @thomreis So what do we conclude **does** cause the problem?

**Comment by kkotov** [comment] 2017-07-17 14:45
@abrinke1, era. If you replace "process = cms.Process('L1TMuonEmulation')" for "process = cms.Process('RAW2DIGI',eras.Run2_2016)" in your L1Trigger/L1TMuonEndCap/test/RunTrackFinder_data.py, it'll start doing the same things

**Comment by kkotov** [comment] 2017-07-17 14:49
@abrinke1 wait, I think I now start seeing it in your setup irrespective of era.

**Comment by kkotov** [comment] 2017-07-17 15:54
I change my conclusion. I never saw this before, but an interplay of local producer and global tag results in the corrupted payload. To reproduce such behavior, try to run the following simple config:

import FWCore.ParameterSet.Config as cms

process = cms.Process('Test')

process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')

from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_data', '')

process.load('L1Trigger.L1TMuonEndCap.fakeEmtfParams_cff')

#process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

readFiles = cms.untracked.vstring()
process.source = cms.Source(
    'PoolSource',
    fileNames = cms.untracked.vstring(['file:/afs/cern.ch/work/t/treis/public/forKristian/9ED0BEE9-2E3F-E711-B04D-A0369F6369D2.root']),
    skipEvents = cms.untracked.uint32(260)
    )
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(10) )

process.l1ecv = cms.EDAnalyzer("L1TMuonEndcapViewer")

process.p = cms.Path(process.l1ecv)

It'll reproduce the problem that we see in a more complicated environment. On the other hand, commenting out either the global tag or the fake producer helps to avoid the problem and well as keeping them both and uncommenting the es_prefer statement. I'm shocked.

**Comment by kkotov** [comment] 2017-07-18 10:07
If needed, one can, of course, prefer local EMTF conditions from the "fake" producer adding:
process.es_prefer_fake = cms.ESPrefer("L1TMuonEndCapParamsESProducer","emtfParams")

**Comment by kkotov** [comment] 2017-07-18 10:10
Although, one can, of course, prefer local EMTF conditions from the "fake" producer adding:
process.es_prefer_fake = cms.ESPrefer("L1TMuonEndCapParamsESProducer","emtfParams")
, it seems to produce corrupted payload as well.

**Comment by kkotov** [comment] 2017-07-18 18:52
Summary on how to reproduce the problem:

cmsrel CMSSW_9_2_5
cd CMSSW_9_2_5
rmdir src
tar -xzf ~kkotov/public/src.tgz
cd src
scram b
cmsRun q.py

README.md gives few insights on how to avoid this problem. Nonetheless, I don't understand its origin.

**Comment by kkotov** [comment] 2017-07-19 05:28
I think I now understand the issue better. One has to change https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapParamsESProducer.cc#L61 :

std::shared_ptr<L1TMuonEndCapParams> pEMTFParams(data_.getWriteInstance());
->
std::shared_ptr<L1TMuonEndCapParams> pEMTFParams(new L1TMuonEndCapParams(*data_.getWriteInstance()));

Looks like the framework simply deletes conditions that are no longer needed and I didn't provide a spare copy of those. It was my error.

**Comment by fwyzard** [comment] 2017-07-19 06:30
Hi @kkotov,
```
std::shared_ptr pEMTFParams(new L1TMuonEndCapParams(*data_.getWriteInstance()));
```
is better written as
```
auto pEMTFParams = std::make_shared<L1TMuonEndCapParams>(*data_.getWriteInstance());
```

However, if I remember correctly, there used to be a way to ask the framework not to delete conditions (immediately) after you read them.

I have a doubt though - are you holding to the conditions after their IOV is elapsed ?

.A

**Comment by kkotov** [comment] 2017-07-19 07:11
Hi @fwyzard,

Indeed, std::make_shared looks even better. I wasn't holding on to the conditions and I didn't need to extend their lifetime after IOV elapses. I just accidentally gave away to the framework a pointer that the local producer owns through it's lifetime. What I was really supposed to do is to give a copy of condition object wrapped in the std::shared_ptr (i.e. gave away the ownership).

It is a bit of an engineered problem with EndCapParamsHelper, that is overly complicated solution in the particular case. I inherited it and I now think of removing it someday from the code.

**Comment by abrinke1** [comment] 2017-07-19 15:39
Hi @thomreis @pkontaxa , when you have a chance, can you try running the problematic 2016 / 2017 jobs with this one line changed:

std::shared_ptr pEMTFParams(new L1TMuonEndCapParams(*data_.getWriteInstance()));

changed to:

auto pEMTFParams = std::make_shared<L1TMuonEndCapParams>(*data_.getWriteInstance());

It would be great to see if this fixes it.

Thanks much,
Andrew

**Comment by thomreis** [comment] 2017-07-19 15:42
Hi @abrinke1 ,
I just did that and this prevents the crashes indeed.
The LUT versions now come from the fakeEmtfParams.py file. Is this what is intended?

Regards,
Thomas

**Comment by jiafulow** [comment] 2017-07-21 11:49
Hi @kkotov ,

For my own curiosity, why can't we simply use L1TMuonEndCapParams rather than having to use the helper (EndCapParamsHelper)? I can't imagine we need such a fine-grained read/write control.

Jia Fu

**Comment by kkotov** [comment] 2017-07-21 13:07
@jiafulow , we can. In the EMTF we use the helper only to give meaningful names via accessors and mutators (e.g. the PhiWindow field is really manipulated with *PcLutVersion* functions). Read/write control was introduced for the "expensive to copy" payloads such as CaloParams. But then the recipe was cloned everywhere, including where it didn't have any practical sense. I'd simplify it in some of the future PRs.

**Comment by jiafulow** [comment] 2017-07-21 13:20
@kkotov , thanks for the answer. I like to think simpler is better, but it's fine.

**Comment by thomreis** [comment] 2017-07-21 15:32
One other reason for using the helper was that we do not need to touch the CondFormats package if we make a simple change to the L1TMuonEndCapParams. That way we could avoid the sign off of the database people for changes that did not affect the record itself.

**Comment by jiafulow** [comment] 2017-07-21 16:14
Ok, that's good to know. I wasn't suggesting that it should be changed.

**Comment by abrinke1** [comment] 2017-07-25 17:47
Hi all,

Following also on the discussion in PR #591 , I've created a new branch to help debug the problem further: https://github.com/abrinke1/cmssw/tree/EMTF_July_2017_conditions_fix

You should be able to run it as follows:

cmsrel CMSSW_9_2_5_patch2
cd CMSSW_9_2_5_patch2/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic -u cms-l1t-offline:l1t-integration-CMSSW_9_2_5_patch2
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TMuon.git L1Trigger/L1TMuon/data
git remote add abrinke1 git@github.com:abrinke1/cmssw.git
git fetch abrinke1
git cms-merge-topic -u abrinke1:EMTF_July_2017_conditions_fix
scram b clean; scram b -j 6
cd L1Trigger/L1TMuonEndCap/
cmsRun test/RunTrackFinder_data.py

In RunTrackFinder_data.py, I have the following line un-commented out:
process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

This results in output like the following, running over 2016 data:

Begin processing the 1st record. Run 282650, Event 51338761, LumiSection 99
Do we have new conditions? Yes (1) or no (0)? -- 1
  * Before updating conditions, fw_version_ = 999999, pt_lut_version_ = 888888, pc_lut_version_ = 777777
    - Getting firmware version from ConditionHelper: version = 47214
    - Getting pT LUT version from ConditionHelper: version = 1 (lowest bits of 1)
    - Getting PC LUT version from ConditionHelper: version = 20161006

The firmware version for this event is correct, but I think the pT LUT version is not; and the PC LUT version is definitely not correct.  @kkotov , do you have any idea why this might be happening?  Did your AlCa / GT requests you referred to above go through?  Or is this unrelated?

Thanks much,
Andrew

**Comment by kkotov** [comment] 2017-07-26 04:59
You have L1TMuonEndCapParams_Stage2v0_hlt in the Global Tag. My request for L1TMuonEndCapParams_Stage2v1_hlt is still pending. I'll write a HN post for AlCa.

**Comment by abrinke1** [comment] 2017-07-26 08:06
OK, that's very good to know.  Is there a way I can explicitly invoke "L1TMuonEndCapParams_Stage2v1_hlt" rather than "L1TMuonEndCapParams_Stage2v0_hlt ", to see if the emulator will work once AlCa updates the global tag?

Thanks much,
Andrew

**Comment by abrinke1** [comment] 2017-07-26 10:37
Hi @rekovic , @thomreis , @kkotov , all,

I just added a commit to properly handle the FW/pT LUT/PC lut versions, as well as pT LUT XMLs ("forests"), for 2016 and 2017 data and MC:

https://github.com/abrinke1/cmssw/commits/EMTF_July_2017_conditions_fix

This involved creating 4 new fakeEmtfParams files, which would have to be invoked by the L1T emulator.  Furthermore, to re-emulate data, I had to include the following line in my python config:

process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","emtfParamsSource")

I'm not sure if this the best solution, or correct, or even doable in the L1T emulation framework ... so I wanted to get some thoughts.  I see that fakeEmtfParams is invoked many places, so I'd at least want to not break these workflows:

http://cmslxr.fnal.gov/search?v=CMSSW_9_2_4&_string=fakeEmtfParams&_advanced=&_filestring=&_casesensitive=

Then somewhere in the L1TNtuple chain, for example, we would need switches on which fakeEmtfParams to include.  The reason for all this is that we can't access the correct pT LUT XMLs until central CMSSW has included the PR with the database changes from @kkotov , so these still have to be specified by hand - but specified differently for 2016 and 2017.

Let me know what y'all think, or if you have any questions.

Best,
Andrew

**Comment by kkotov** [comment] 2017-07-26 11:06
I think you can ignore all but the first line from the lxr search. And as for the hackConditions, I hope we will close this subject one day. In other words, you should be the only one who uses fake producers.

**Comment by abrinke1** [comment] 2017-07-26 13:42
@rekovic @thomreis @kkotov Does anyone know if I can add an era-based switch here?

https://github.com/abrinke1/cmssw/blob/EMTF_July_2017_conditions_fix/L1Trigger/L1TMuon/python/hackConditions_cff.py#L27

Does stage2L1Trigger contain a "year" or "era" property, or could I import another configuration to use as a switch?  Also, is there anything to distinguish between data and MC?  (This is less important.)

Thanks,
Andrew

**Comment by nsmith-** [comment] 2017-07-26 13:46
Something like that is used here: https://github.com/abrinke1/cmssw/blob/EMTF_July_2017_conditions_fix/L1Trigger/L1TCalorimeter/python/hackConditions_cff.py#L40
It looks like you could import this modifier and use it: https://github.com/abrinke1/cmssw/blob/EMTF_July_2017_conditions_fix/Configuration/Eras/python/Era_Run2_2016_cff.py

**Comment by thomreis** [comment] 2017-07-26 13:49
I though using eras as a switch with isChosen is not allowed anymore.
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriverEras

**Comment by abrinke1** [comment] 2017-07-26 14:30
It's not clear to me that "Run2_2016" and "Run2_2017" are even mutually exclusive:

https://github.com/abrinke1/cmssw/blob/EMTF_July_2017_conditions_fix/Configuration/Eras/python/Era_Run2_2017_cff.py#L13

The L1TCalorimeter hackConditions use the pA_2016 *Modifier*, but I assume these aren't necessarily comprehensive - i.e. you wouldn't cover all 2017 data just by OR-ing together all the Modifier_XXX_2017_XXX_cff.py files here:

https://github.com/abrinke1/cmssw/tree/EMTF_July_2017_conditions_fix/Configuration/Eras/python

That said, I honestly don't know how these things work ... so further expert advice is certainly welcome!

**Comment by abrinke1** [comment] 2017-07-26 14:34
@thomreis I notice we use eras (e.g. run2_2016) all over the L1T NTuple code:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions

Is all this being removed?  Any idea how, or when?

**Comment by thomreis** [comment] 2017-07-26 14:52
How and when I cannot say.
But I remember that we could not get new configurations using eras in combination with if statements merged in CMSSW. This was for the offline DQM.
I think @rekovic knows the details on what to do.

**Comment by abrinke1** [comment] 2017-08-03 13:23
@rekovic Can we talk about the 2016 / 2017 switches in the emulator?  I'd be happy to include @thomreis as well ... but I'd like to close this out soon, so we can perform 2016 re-emulation without private, multi-file-edit hacks.

**Comment by abrinke1** [comment] 2017-08-09 16:28
Issue taken up in PR #604

**Comment by jiafulow** [comment] 2018-02-21 05:14
Isn't this resolved? Can it be closed?

**Comment by abrinke1** [comment] 2018-02-21 09:03
I think so.

**Closed as completed by abrinke1** 2018-02-21 09:03 UTC
